/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PublicKey {
    #[serde(rename = "mechanisms")]
    pub mechanisms: Vec<crate::models::KeyMechanism>,
    #[serde(rename = "type")]
    pub _type: crate::models::KeyType,
    #[serde(rename = "key")]
    pub key: Box<crate::models::KeyPublicData>,
    #[serde(rename = "operations")]
    pub operations: i32,
}

impl PublicKey {
    pub fn new(mechanisms: Vec<crate::models::KeyMechanism>, _type: crate::models::KeyType, key: crate::models::KeyPublicData, operations: i32) -> PublicKey {
        PublicKey {
            mechanisms,
            _type,
            key: Box::new(key),
            operations,
        }
    }
}


