/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserRole {
    #[serde(rename = "Administrator")]
    Administrator,
    #[serde(rename = "Operator")]
    Operator,
    #[serde(rename = "Metrics")]
    Metrics,
    #[serde(rename = "Backup")]
    Backup,

}

impl ToString for UserRole {
    fn to_string(&self) -> String {
        match self {
            Self::Administrator => String::from("Administrator"),
            Self::Operator => String::from("Operator"),
            Self::Metrics => String::from("Metrics"),
            Self::Backup => String::from("Backup"),
        }
    }
}

impl Default for UserRole {
    fn default() -> UserRole {
        Self::Administrator
    }
}




