/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DistinguishedName {
    #[serde(rename = "countryName")]
    pub country_name: String,
    #[serde(rename = "stateOrProvinceName")]
    pub state_or_province_name: String,
    #[serde(rename = "localityName")]
    pub locality_name: String,
    #[serde(rename = "organizationName")]
    pub organization_name: String,
    #[serde(rename = "organizationalUnitName")]
    pub organizational_unit_name: String,
    #[serde(rename = "commonName")]
    pub common_name: String,
    #[serde(rename = "emailAddress")]
    pub email_address: String,
}

impl DistinguishedName {
    pub fn new(country_name: String, state_or_province_name: String, locality_name: String, organization_name: String, organizational_unit_name: String, common_name: String, email_address: String) -> DistinguishedName {
        DistinguishedName {
            country_name,
            state_or_province_name,
            locality_name,
            organization_name,
            organizational_unit_name,
            common_name,
            email_address,
        }
    }
}


