/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyType {
    #[serde(rename = "RSA")]
    RSA,
    #[serde(rename = "Curve25519")]
    Curve25519,
    #[serde(rename = "EC_P224")]
    ECP224,
    #[serde(rename = "EC_P256")]
    ECP256,
    #[serde(rename = "EC_P384")]
    ECP384,
    #[serde(rename = "EC_P521")]
    ECP521,
    #[serde(rename = "Generic")]
    Generic,

}

impl ToString for KeyType {
    fn to_string(&self) -> String {
        match self {
            Self::RSA => String::from("RSA"),
            Self::Curve25519 => String::from("Curve25519"),
            Self::ECP224 => String::from("EC_P224"),
            Self::ECP256 => String::from("EC_P256"),
            Self::ECP384 => String::from("EC_P384"),
            Self::ECP521 => String::from("EC_P521"),
            Self::Generic => String::from("Generic"),
        }
    }
}

impl Default for KeyType {
    fn default() -> KeyType {
        Self::RSA
    }
}




