/*
 * NetHSM
 *
 * All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All <a href=\"https://tools.ietf.org/html/rfc4648#section-4\">base64</a> encoded values are Big Endian.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SystemInfo {
    #[serde(rename = "firmwareVersion")]
    pub firmware_version: String,
    #[serde(rename = "softwareVersion")]
    pub software_version: String,
    #[serde(rename = "hardwareVersion")]
    pub hardware_version: String,
    #[serde(rename = "buildTag")]
    pub build_tag: String,
}

impl SystemInfo {
    pub fn new(firmware_version: String, software_version: String, hardware_version: String, build_tag: String) -> SystemInfo {
        SystemInfo {
            firmware_version,
            software_version,
            hardware_version,
            build_tag,
        }
    }
}


